# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Editor (and arguments) to use for the `open-editor` command. The
# following placeholders are defined: * `{file}`: Filename of the file
# to be edited. * `{line}`: Line in which the caret is found in the
# text. * `{column}`: Column in which the caret is found in the text. *
# `{line0}`: Same as `{line}`, but starting from index 0. * `{column0}`:
# Same as `{column}`, but starting from index 0.
# Type: ShellCommand
c.editor.command = ['urxvt', '-e', 'vim', '{}']

config.bind('o', 'set-cmd-text --space :open --tab')
config.bind('<Ctrl-i>', 'leave-mode', mode='insert')
c.scrolling.smooth=True
c.statusbar.widgets=['keypress', 'url', 'scroll', 'progress']
c.tabs.background=True
c.tabs.last_close='default-page'
c.tabs.show='always'
c.url.default_page='https://google.com'
c.url.searchengines={'DEFAULT':'https://google.com/search?q={}', 'ddg':'https://ducjducjgo.com?q={}'}
c.url.start_pages='https://google.com'
c.confirm_quit=["multiple-tabs", "downloads"]
c.downloads.location.directory='/home/agabey/Downloads/'
c.hints.chars="asdfghjkleiworu"
c.tabs.indicator.width=0
config.bind(',a', 'spawn --userscript qute-pass')
